package com.quickcamel.winnow.palindromes.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "palindrome_task")
public class PalindromeTaskEntity {

    public enum Status {
        SUBMITTED,
        STARTED,
        COMPLETED
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String task;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private Status status;

    @DynamoDBAttribute
    private Long submitted;
    @DynamoDBAttribute
    private Long started;
    @DynamoDBAttribute
    private Long completed;

    @DynamoDBAttribute
    private String text;

    @DynamoDBAttribute
    private Integer largestPalindromeLength;
    @DynamoDBAttribute
    private String largestPalindrome;

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Long getSubmitted() {
        return submitted;
    }

    public void setSubmitted(Long submitted) {
        this.submitted = submitted;
    }

    public Long getStarted() {
        return started;
    }

    public void setStarted(Long started) {
        this.started = started;
    }

    public Long getCompleted() {
        return completed;
    }

    public void setCompleted(Long completed) {
        this.completed = completed;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getLargestPalindromeLength() {
        return largestPalindromeLength;
    }

    public void setLargestPalindromeLength(Integer largestPalindromeLength) {
        this.largestPalindromeLength = largestPalindromeLength;
    }

    public String getLargestPalindrome() {
        return largestPalindrome;
    }

    public void setLargestPalindrome(String largestPalindrome) {
        this.largestPalindrome = largestPalindrome;
    }

    public PalindromeTaskEntity withTask(final String task) {
        this.task = task;
        return this;
    }

    public PalindromeTaskEntity withStatus(final Status status) {
        this.status = status;
        return this;
    }

    public PalindromeTaskEntity withSubmitted(final Long submitted) {
        this.submitted = submitted;
        return this;
    }

    public PalindromeTaskEntity withStarted(final Long started) {
        this.started = started;
        return this;
    }

    public PalindromeTaskEntity withCompleted(final Long completed) {
        this.completed = completed;
        return this;
    }

    public PalindromeTaskEntity withText(final String text) {
        this.text = text;
        return this;
    }

    public PalindromeTaskEntity withLargestPalindromeLength(final Integer largestPalindromeLength) {
        this.largestPalindromeLength = largestPalindromeLength;
        return this;
    }

    public PalindromeTaskEntity withLargestPalindrome(final String largestPalindrome) {
        this.largestPalindrome = largestPalindrome;
        return this;
    }


    @Override
    public String toString() {
        return "PalindromeTask{" +
                "task='" + task + '\'' +
                ", status=" + status +
                ", submitted=" + submitted +
                ", started=" + started +
                ", completed=" + completed +
                ", text='" + text + '\'' +
                ", largestPalindromeLength=" + largestPalindromeLength +
                ", largestPalindrome='" + largestPalindrome + '\'' +
                '}';
    }
}

